############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 4

[[main]]
name = "Service"
url = "service/"
weight = 2

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 5

#[[main]]
#hasChildren = true
#name = "Pages"
#weight = 8

[[main]]
name = "Project"
url = "project/"
weight = 3

#[[main]]
#name = "Pricing"
#parent = "Pages"
#url = "pricing/"

# footer menu
[[footer]]
name = "Legal"
url = "#"
weight = 1

[[footer]]
name = "Sitemap"
url = "#"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "#"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "#"
weight = 4
